on: 

  push:

    branches:
      - staging

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: de3.fcomet.com
        username: ${{ secret.ftps_username }}
        password: ${{ secrets.ftps_password }}
        server-dir : /public_html/staging.com/